import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Generate a comprehensive API 510 Pressure Vessel Inspection Report PDF
 * @param {Object} data - Complete inspection data from all modules
 * @returns {jsPDF} - PDF document instance
 */
export function generateAPI510Report(data) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Color scheme
  const primaryColor = [34, 41, 108]; // Dark blue
  const secondaryColor = [220, 53, 69]; // Red
  const accentColor = [52, 152, 219]; // Light blue
  const textColor = [51, 51, 51]; // Dark gray

  // Helper function to add a new page if needed
  const checkPageBreak = (requiredSpace = 20) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to add section header
  const addSectionHeader = (title, icon = '') => {
    checkPageBreak(30);
    doc.setFillColor(...primaryColor);
    doc.rect(margin, yPosition, pageWidth - 2 * margin, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin + 5, yPosition + 7);
    yPosition += 15;
    doc.setTextColor(...textColor);
  };

  // Helper function to add subsection header
  const addSubsectionHeader = (title) => {
    checkPageBreak(20);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...accentColor);
    doc.text(title, margin, yPosition);
    yPosition += 8;
    doc.setTextColor(...textColor);
  };

  // Helper function to add key-value pair
  const addKeyValue = (key, value, indent = 0) => {
    checkPageBreak(10);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(key + ':', margin + indent, yPosition);
    doc.setFont('helvetica', 'normal');
    const valueText = value !== null && value !== undefined && value !== '' ? String(value) : 'N/A';
    doc.text(valueText, margin + indent + 60, yPosition);
    yPosition += 6;
  };

  // ============================================================
  // COVER PAGE
  // ============================================================
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 80, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('API 510', pageWidth / 2, 35, { align: 'center' });
  doc.setFontSize(20);
  doc.text('Pressure Vessel Inspection Report', pageWidth / 2, 50, { align: 'center' });
  
  doc.setFillColor(...secondaryColor);
  doc.rect(0, 80, pageWidth, 5, 'F');

  yPosition = 100;
  doc.setTextColor(...textColor);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  // Report Header Information
  if (data.reportHeader) {
    const header = data.reportHeader;
    addKeyValue('Report Number', header.reportNumber);
    addKeyValue('Inspection Date', header.inspectionDate);
    addKeyValue('Report Date', header.reportDate);
    addKeyValue('Inspector', header.inspector);
    addKeyValue('Inspector Certification', header.inspectorCertification);
    addKeyValue('Inspection Company', header.company);
    addKeyValue('Customer', header.customer);
    addKeyValue('Facility Location', header.location);
  }

  // Vessel identification
  yPosition += 10;
  if (data.vesselData) {
    const vessel = data.vesselData;
    addSubsectionHeader('Vessel Identification');
    addKeyValue('Tag Number', vessel.tagNumber);
    addKeyValue('Vessel Name', vessel.vesselName);
    addKeyValue('Manufacturer', vessel.manufacturer);
    addKeyValue('Year Built', vessel.yearBuilt);
  }

  // Add footer to cover page
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by API 510 Inspection System', pageWidth / 2, pageHeight - 10, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, pageHeight - 5, { align: 'center' });

  // ============================================================
  // PAGE 2: VESSEL DATA & DESIGN INFORMATION
  // ============================================================
  doc.addPage();
  yPosition = margin;

  addSectionHeader('1. VESSEL DATA & DESIGN INFORMATION');

  if (data.vesselData) {
    const vessel = data.vesselData;
    
    addSubsectionHeader('Design Parameters');
    addKeyValue('Vessel Type', vessel.vesselType);
    addKeyValue('Design Pressure', vessel.designPressure ? `${vessel.designPressure} psi` : 'N/A');
    addKeyValue('Design Temperature', vessel.designTemperature ? `${vessel.designTemperature} °F` : 'N/A');
    addKeyValue('Operating Pressure', vessel.operatingPressure ? `${vessel.operatingPressure} psi` : 'N/A');
    addKeyValue('Material Specification', vessel.materialSpec);
    
    yPosition += 5;
    addSubsectionHeader('Dimensions');
    addKeyValue('Inside Diameter', vessel.insideDiameter ? `${vessel.insideDiameter} in` : 'N/A');
    addKeyValue('Overall Length', vessel.overallLength ? `${vessel.overallLength} ft` : 'N/A');
  }

  // ============================================================
  // CALCULATION RESULTS
  // ============================================================
  yPosition += 10;
  addSectionHeader('2. CALCULATION RESULTS');

  if (data.calculations) {
    const calc = data.calculations;
    
    addSubsectionHeader('Minimum Required Thickness');
    if (calc.minThickness) {
      addKeyValue('Design Pressure', calc.minThickness.designPressure ? `${calc.minThickness.designPressure} psi` : 'N/A');
      addKeyValue('Inside Radius', calc.minThickness.insideRadius ? `${calc.minThickness.insideRadius} in` : 'N/A');
      addKeyValue('Allowable Stress', calc.minThickness.allowableStress ? `${calc.minThickness.allowableStress} psi` : 'N/A');
      addKeyValue('Joint Efficiency', calc.minThickness.jointEfficiency);
      addKeyValue('Corrosion Allowance', calc.minThickness.corrosionAllowance ? `${calc.minThickness.corrosionAllowance} in` : 'N/A');
      addKeyValue('Calculated Min. Thickness', calc.minThickness.result ? `${calc.minThickness.result} in` : 'N/A');
      if (calc.minThickness.formula) {
        yPosition += 3;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        doc.text(`Formula: ${calc.minThickness.formula}`, margin, yPosition);
        yPosition += 6;
      }
    }

    yPosition += 5;
    addSubsectionHeader('Maximum Allowable Working Pressure (MAWP)');
    if (calc.mawp) {
      addKeyValue('Actual Thickness', calc.mawp.actualThickness ? `${calc.mawp.actualThickness} in` : 'N/A');
      addKeyValue('Inside Radius', calc.mawp.insideRadius ? `${calc.mawp.insideRadius} in` : 'N/A');
      addKeyValue('Allowable Stress', calc.mawp.allowableStress ? `${calc.mawp.allowableStress} psi` : 'N/A');
      addKeyValue('Joint Efficiency', calc.mawp.jointEfficiency);
      addKeyValue('Calculated MAWP', calc.mawp.result ? `${calc.mawp.result} psi` : 'N/A');
      if (calc.mawp.formula) {
        yPosition += 3;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        doc.text(`Formula: ${calc.mawp.formula}`, margin, yPosition);
        yPosition += 6;
      }
    }

    yPosition += 5;
    addSubsectionHeader('Remaining Life Assessment');
    if (calc.remainingLife) {
      addKeyValue('Current Thickness', calc.remainingLife.currentThickness ? `${calc.remainingLife.currentThickness} in` : 'N/A');
      addKeyValue('Required Thickness', calc.remainingLife.requiredThickness ? `${calc.remainingLife.requiredThickness} in` : 'N/A');
      addKeyValue('Corrosion Rate', calc.remainingLife.corrosionRate ? `${calc.remainingLife.corrosionRate} in/yr` : 'N/A');
      addKeyValue('Remaining Life', calc.remainingLife.result ? `${calc.remainingLife.result} years` : 'N/A');
      if (calc.remainingLife.formula) {
        yPosition += 3;
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        doc.text(`Formula: ${calc.remainingLife.formula}`, margin, yPosition);
        yPosition += 6;
      }
    }
  }

  // ============================================================
  // THICKNESS ANALYSIS
  // ============================================================
  checkPageBreak(40);
  yPosition += 10;
  addSectionHeader('3. THICKNESS ANALYSIS');

  if (data.thicknessData && data.thicknessData.measurements && data.thicknessData.measurements.length > 0) {
    const measurements = data.thicknessData.measurements;
    
    // Create table for thickness measurements
    const tableData = measurements.map(m => [
      m.location || 'N/A',
      m.component || 'N/A',
      m.originalThickness ? `${m.originalThickness}"` : 'N/A',
      m.currentThickness ? `${m.currentThickness}"` : 'N/A',
      m.minRequired ? `${m.minRequired}"` : 'N/A',
      m.status || 'N/A'
    ]);

    doc.autoTable({
      startY: yPosition,
      head: [['Location', 'Component', 'Original', 'Current', 'Min Required', 'Status']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 30 },
        2: { cellWidth: 25 },
        3: { cellWidth: 25 },
        4: { cellWidth: 25 },
        5: { cellWidth: 25 }
      },
      margin: { left: margin, right: margin }
    });

    yPosition = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(10);
    doc.text('No thickness measurements recorded.', margin, yPosition);
    yPosition += 10;
  }

  // ============================================================
  // EXTERNAL INSPECTION
  // ============================================================
  checkPageBreak(40);
  yPosition += 10;
  addSectionHeader('4. EXTERNAL INSPECTION');

  if (data.externalInspection) {
    const ext = data.externalInspection;
    
    addSubsectionHeader('Visual Inspection Results');
    addKeyValue('Overall Condition', ext.overallCondition);
    addKeyValue('Corrosion Present', ext.corrosionPresent);
    addKeyValue('Coating Condition', ext.coatingCondition);
    addKeyValue('Insulation Condition', ext.insulationCondition);
    
    if (ext.findings && ext.findings.length > 0) {
      yPosition += 5;
      addSubsectionHeader('Findings');
      ext.findings.forEach((finding, index) => {
        checkPageBreak(15);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${finding.description || 'N/A'}`, margin, yPosition);
        yPosition += 6;
        doc.setFont('helvetica', 'normal');
        doc.text(`   Severity: ${finding.severity || 'N/A'}`, margin, yPosition);
        yPosition += 6;
        if (finding.recommendation) {
          doc.text(`   Recommendation: ${finding.recommendation}`, margin, yPosition);
          yPosition += 6;
        }
      });
    }

    if (ext.notes) {
      yPosition += 5;
      addSubsectionHeader('Inspector Notes');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const splitNotes = doc.splitTextToSize(ext.notes, pageWidth - 2 * margin);
      splitNotes.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
    }
  }

  // ============================================================
  // INTERNAL INSPECTION
  // ============================================================
  checkPageBreak(40);
  yPosition += 10;
  addSectionHeader('5. INTERNAL INSPECTION');

  if (data.internalInspection) {
    const int = data.internalInspection;
    
    addSubsectionHeader('Internal Inspection Results');
    addKeyValue('Inspection Method', int.inspectionMethod);
    addKeyValue('Overall Condition', int.overallCondition);
    addKeyValue('Internal Corrosion', int.internalCorrosion);
    addKeyValue('Pitting Present', int.pittingPresent);
    addKeyValue('Cracking Detected', int.crackingDetected);
    
    if (int.findings && int.findings.length > 0) {
      yPosition += 5;
      addSubsectionHeader('Findings');
      int.findings.forEach((finding, index) => {
        checkPageBreak(15);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${finding.description || 'N/A'}`, margin, yPosition);
        yPosition += 6;
        doc.setFont('helvetica', 'normal');
        doc.text(`   Location: ${finding.location || 'N/A'}`, margin, yPosition);
        yPosition += 6;
        doc.text(`   Severity: ${finding.severity || 'N/A'}`, margin, yPosition);
        yPosition += 6;
      });
    }

    if (int.notes) {
      yPosition += 5;
      addSubsectionHeader('Inspector Notes');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const splitNotes = doc.splitTextToSize(int.notes, pageWidth - 2 * margin);
      splitNotes.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
    }
  }

  // ============================================================
  // PRESSURE RELIEF DEVICES
  // ============================================================
  checkPageBreak(40);
  yPosition += 10;
  addSectionHeader('6. PRESSURE RELIEF DEVICES');

  if (data.reliefDevices && data.reliefDevices.devices && data.reliefDevices.devices.length > 0) {
    const devices = data.reliefDevices.devices;
    
    devices.forEach((device, index) => {
      checkPageBreak(30);
      addSubsectionHeader(`Relief Device ${index + 1}`);
      addKeyValue('Device Type', device.deviceType);
      addKeyValue('Set Pressure', device.setPressure ? `${device.setPressure} psi` : 'N/A');
      addKeyValue('Capacity', device.capacity);
      addKeyValue('Condition', device.condition);
      addKeyValue('Last Test Date', device.lastTestDate);
      addKeyValue('Next Test Due', device.nextTestDue);
      yPosition += 5;
    });
  } else {
    doc.setFontSize(10);
    doc.text('No pressure relief devices recorded.', margin, yPosition);
    yPosition += 10;
  }

  // ============================================================
  // INSPECTION PLANNING
  // ============================================================
  checkPageBreak(40);
  yPosition += 10;
  addSectionHeader('7. INSPECTION PLANNING & INTERVALS');

  if (data.inspectionPlanning) {
    const plan = data.inspectionPlanning;
    
    addSubsectionHeader('Inspection Intervals');
    addKeyValue('Damage Mechanism', plan.damageMechanism);
    addKeyValue('Inspection Effectiveness', plan.inspectionEffectiveness);
    addKeyValue('Consequence Category', plan.consequenceCategory);
    addKeyValue('Calculated Interval', plan.calculatedInterval ? `${plan.calculatedInterval} years` : 'N/A');
    addKeyValue('Recommended Interval', plan.recommendedInterval ? `${plan.recommendedInterval} years` : 'N/A');
    addKeyValue('Next Internal Inspection', plan.nextInternalDate);
    addKeyValue('Next External Inspection', plan.nextExternalDate);
    
    if (plan.notes) {
      yPosition += 5;
      addSubsectionHeader('Planning Notes');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const splitNotes = doc.splitTextToSize(plan.notes, pageWidth - 2 * margin);
      splitNotes.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
    }
  }

  // ============================================================
  // EXECUTIVE SUMMARY
  // ============================================================
  checkPageBreak(40);
  yPosition += 10;
  addSectionHeader('8. EXECUTIVE SUMMARY');

  if (data.executiveSummary) {
    const summary = data.executiveSummary;
    
    addSubsectionHeader('Overall Condition');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(summary.overallCondition || 'N/A', margin, yPosition);
    yPosition += 10;
    
    if (summary.keyFindings) {
      addSubsectionHeader('Key Findings');
      doc.setFont('helvetica', 'normal');
      const splitFindings = doc.splitTextToSize(summary.keyFindings, pageWidth - 2 * margin);
      splitFindings.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
      yPosition += 5;
    }
    
    if (summary.recommendations) {
      addSubsectionHeader('Recommendations');
      doc.setFont('helvetica', 'normal');
      const splitRecs = doc.splitTextToSize(summary.recommendations, pageWidth - 2 * margin);
      splitRecs.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
      yPosition += 5;
    }
    
    addKeyValue('Next Inspection Date', summary.nextInspectionDate);
  }

  // ============================================================
  // CERTIFICATIONS
  // ============================================================
  checkPageBreak(60);
  yPosition += 10;
  addSectionHeader('9. INSPECTOR CERTIFICATION');

  if (data.certifications) {
    const cert = data.certifications;
    
    if (cert.inspectorStatement) {
      addSubsectionHeader('Inspector Statement');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const splitStatement = doc.splitTextToSize(cert.inspectorStatement, pageWidth - 2 * margin);
      splitStatement.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
      yPosition += 10;
    }
    
    addKeyValue('Certification Date', cert.certificationDate);
    addKeyValue('Next Due Date', cert.nextDueDate);
    
    if (cert.jurisdictionalRequirements) {
      yPosition += 5;
      addSubsectionHeader('Jurisdictional Requirements');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const splitReqs = doc.splitTextToSize(cert.jurisdictionalRequirements, pageWidth - 2 * margin);
      splitReqs.forEach(line => {
        checkPageBreak(10);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
    }

    // Signature line
    yPosition += 15;
    checkPageBreak(30);
    doc.setDrawColor(0, 0, 0);
    doc.line(margin, yPosition, margin + 80, yPosition);
    yPosition += 5;
    doc.setFontSize(9);
    doc.text('Inspector Signature', margin, yPosition);
    
    doc.line(pageWidth - margin - 80, yPosition - 5, pageWidth - margin, yPosition - 5);
    doc.text('Date', pageWidth - margin - 20, yPosition);
  }

  // ============================================================
  // ADD PAGE NUMBERS
  // ============================================================
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }

  return doc;
}

/**
 * Download the generated PDF
 * @param {Object} data - Complete inspection data
 * @param {string} filename - Optional filename (defaults to report number or timestamp)
 */
export function downloadAPI510Report(data, filename) {
  const doc = generateAPI510Report(data);
  const reportNumber = data.reportHeader?.reportNumber || `API510_${Date.now()}`;
  const finalFilename = filename || `${reportNumber}_Inspection_Report.pdf`;
  doc.save(finalFilename);
}
